#! /usr/bin/env python3

#    Copyright (C) 2015  Zumium
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import socket
import sys

def init_socket():
	s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
	s.bind(('127.0.0.1',6566))
	return s

def main():
	op=sys.argv[1]
	s=init_socket()
	SERVER=('127.0.0.1',6565)
	if op=='quit':
		s.sendto("Quit".encode('UTF-8'),SERVER)
		print("Shadowsocks Quit\n")
	elif op=='close':
		s.sendto("Close".encode('UTF-8'),SERVER)
		print("Shadowsocks Close\n")
	else:
		s.sendto("Change {0}".format(op).encode('UTF-8'),SERVER)
		print("Server changed to {0}\n".format(op))
	s.close()

if __name__=='__main__':
	main()
